
services:
  odinson-rest-api:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
  hasura:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  postgres:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  backend:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  frontend:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  nginx:
    environment:
      URL_UPLOAD: 10.5.0.7
      URL_ODINSON: 10.5.0.8
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  file_upload:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1