version: "2.3"
services:
  prisma:
    container_name: colrc-v2-prisma
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4466:4466"
    env_file:
      - ./.env
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql  # or `postgres`
            migrations: true
            host: mysql
            port: 3306        # or `5432` for `postgres`
            user: ${DB_USERNAME}
            password: ${DB_PASSWORD}
  mysql:
    container_name: colrc-v2-mysql-db
    # see https://hub.docker.com/_/mysql/
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      # SQL scripts in this directory will be executed in alphabetical order
      - "./misc/sql:/docker-entrypoint-initdb.d"
    healthcheck:
        # NOTE: https://stackoverflow.com/a/44488707
        test: ["CMD", "mysqladmin", "-u$DB_USERNAME", "-p$DB_PASSWORD", "ping"]
        start_period: 10s
        interval: 30s
        timeout: 20s
        retries: 10
  backend:
    container_name: colrc-v2-backend
    build:
      context: ./backend
      # specify .dev or .prod variant
      dockerfile: Dockerfile.prod
      labels:
        edu.arizona.colrc.description: "API for COLRC v2"
    depends_on:
      - mysql
      - prisma
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    environment:
      DB_HOST: mysql
    volumes:
      - ./backend:/app:rw
  frontend:
    container_name: colrc-v2-frontend
    build:
      context: ./frontend
      labels:
        edu.arizona.colrc.description: "Frontend for COLRC v2"
    depends_on:
      - backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src:rw
      - ./frontend/public:/app/public:rw
volumes:
  # FIXME: this should point to a pre-populated DB for deployment;
  # Consider ENV variable for volume path
  mysql: