apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:  
    app: psql
    ver: psql-1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "./misc/db_data"
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
spec:
  selector:
    matchLabels:
      app: psql
      ver: psql-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-initdb-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "./misc/sql"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-initdb-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi


---

apiVersion: v1
kind: Deployment
metadata:
  name: colrc
  labels:
    app: colrc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colrc
  template:
    metadata:
      labels:
        app: colrc
    spec:
      containers:   
      - name: postgres
        image: docker.io/library/postgres:12
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: postgres-initdb 
            readOnly: true
            defaultMode: 07
          - mountPath: /var/lib/postgresql/data 
            name: pgdatavol
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: 11chastq
        - name: POSTGRES_DB
          value: colrc
        ports:
          - containerPort: 5432
            hostPort: 5432
            protocol: TCP            
      volumes:
        - name: postgres-initdb
          hostPath: 
            path: /home/amyfou/colrc-v2/misc/sql 
            type: Directory
          configMap:
            name: postgresql-initdb-config
          persistentVolumeClaim:
            claimName: postgres-initdb-pv-claim
          
        - name: pgdatavol
          hostPath:
            path: /home/amyfou/colrc-v2/misc/db_data
            type: Directory
          persistentVolumeClaim:
            claimName: postgres-volume-claim