# based on https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
FROM node:12

# Create app directory
WORKDIR /app

# Bundle app source
COPY . .

# Install app dependencies
RUN npm install

EXPOSE 4000
#CMD ["sleep", "100"]
CMD [ "sh", "-c", "npm i && npm run dev" ]
#CMD ["npm", "run"]
