FROM debian:11 AS builder

ENV NGINX_VERSION=1.19.7 \
    DAV_VERSION=3.0.0 \
    ECHO_VERSION=0.62 \
    FILE_UPLOAD_VERSION=2.3.0 \
    HTTP_AUTH_PAM_VERSION=1.5.2 \
    HTTP_SUBSTITUTIONS_FILTER_VERSION=0.6.4 \
    UPSTREAM_FAIR_VERSION=0.1.3 \
    NGINX_BUILD_ASSETS_DIR=/var/lib/docker-nginx \
    NGINX_BUILD_ROOT_DIR=/var/lib/docker-nginx/rootfs 

ARG WITH_DEBUG=false
ARG WITH_DAV=true
ARG WITH_ECHO=true
ARG WITH_FILE_UPLOAD=true
ARG WITH_HTTP_AUTH_PAM=true
ARG WITH_HTTP_SUBSTITUTIONS_FILTER=true
ARG WITH_UPSTREAM_FAIR=true

RUN addgroup --system --gid 101 nginx \
    && adduser --system --disabled-login --ingroup nginx --no-create-home --home /nonexistent --gecos "nginx user" --shell /bin/false --uid 101 nginx 

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
      wget ca-certificates make gcc g++ pkg-config perl

RUN apt-get update \
 && apt-get install -yyq netcat-openbsd 

COPY assets/build/ ${NGINX_BUILD_ASSETS_DIR}/

RUN chmod a+x ${NGINX_BUILD_ASSETS_DIR}/install.sh

RUN ${NGINX_BUILD_ASSETS_DIR}/install.sh

COPY entrypointDev.sh ${NGINX_BUILD_ROOT_DIR}/sbin/entrypointDev.sh

RUN chmod 755 ${NGINX_BUILD_ROOT_DIR}/sbin/entrypointDev.sh

FROM debian:11

LABEL maintainer="colrc@thecolrc.org"

RUN addgroup --system --gid 101 nginx \
    && adduser --system --disabled-login --ingroup nginx --no-create-home --home /nonexistent --gecos "nginx user" --shell /bin/false --uid 101 nginx 

ENV NGINX_SITECONF_DIR=/etc/nginx/sites-enabled \
    NGINX_LOG_DIR=/var/log/nginx \
    NGINX_TEMP_DIR=/var/lib/nginx \
    NGINX_CACHE_DIR=/var/cache/nginx \
    NGINX_HTML_DIR=/var/www/colrc \
    NGINX_FILE_DIR=/var/www/colrc/files

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    ca-certificates curl libssl1.1 libxslt1.1 libgd3 libgeoip1 rsync unzip gettext-base \
 && rm -rf /var/lib/apt/lists/*


# two-step copy
COPY --from=builder /var/lib/docker-nginx/rootfs /rootfs
RUN rsync -rtvazP /rootfs/* / \
    && rm -rf /rootfs

# copy texts and audio files into the nginx file directory
# make sure to add the actual Dropbox share link to end of the curl command!
#RUN mkdir -p ${NGINX_FILE_DIR} \
#    && cd ${NGINX_FILE_DIR} \
#    && curl -Lo audio.zip https://www.dropbox.com/sh/jtd0hw3r97rj48q/AADPJFTY0KvJnz83zK97vZh0a?dl=0  \ 
#    && unzip audio.zip -x / \
#    && rm -f audio.zip

# COPY ./assets/build/config/default.conf /etc/nginx/conf.d
# COPY ./assets/build/config/nginx.conf /etc/nginx.conf
# COPY ./assets/build/config/sites-enabled/colrc.template /etc/nginx/sites-enabled/colrc

RUN mkdir -p ${NGINX_FILE_DIR} && touch ${NGINX_FILE_DIR}/nothing.txt

RUN chmod 755 ${NGINX_FILE_DIR} && chmod 644 ${NGINX_FILE_DIR}/*

RUN chown -R nginx:nginx /etc/nginx \
    && chmod -R go+rw /etc/nginx \
    # && sed -i 's,listen       80,listen       8081,' /etc/nginx/templates/colrc.template \
    && sed -i '/user  nginx;/d' /etc/nginx/nginx.conf \
    && sed -i 's,/var/run/nginx.pid,/tmp/nginx.pid,' /etc/nginx/nginx.conf \
    && sed -i "/^http {/a \    proxy_temp_path /tmp/proxy_temp;\n    client_body_temp_path /tmp/client_temp;\n    fastcgi_temp_path /tmp/fastcgi_temp;\n    uwsgi_temp_path /tmp/uwsgi_temp;\n    scgi_temp_path /tmp/scgi_temp;\n" /etc/nginx/nginx.conf \
    # && chown -R nginx:nginx /var/cache/nginx \
    # && chmod -R go+rw /var/cache/nginx \
    && chown -R nginx:nginx /var/log/nginx \
    && chmod -R go+rw /var/log/nginx 
    # && chown -R nginx:nginx /var/run/nginx-agent \
    # && chmod -R go+w /var/run/nginx-agent \
    # && ln -sf /dev/stdout /var/log/nginx-agent/agent.log

EXPOSE 80/tcp 443/tcp 1935/tcp

ENTRYPOINT ["/sbin/entrypointDev.sh"]

# COPY --from=colrc-v2_frontend /app/build /var/www/colrc

CMD ["/usr/sbin/nginx"]

# CMD ["nginx", "-g", "daemon off;"]


